### ISSUE TITLE
missing type is not inferred correctly

### ISSUE THREAD

**Issue by untitaker** [sbrunner/jsonschema-gentypes#469]
`{"properties": {"foo": {"type": "string"}}, "required": "foo"}` is recognized by json schema validators as being a JSON object, but jsonschema-gentypes converts that into `Any`

I cannot find any indication in the spec as to why `type` can be omitted. Perhaps it is an artifact of older specs?

**Comment by untitaker** [comment]
I think what is incorrect or at least suboptimal is that the required property "foo" is not enforced by the generated types even though jsonschema is unambigous about the fact that it is required. That must be the reason why every implementation of jsonschema validation I have seen does have type inferrence rules, because otherwise it's not possible to do something useful with the above example. There is no chance that a schema can allow the payload to be both an integer and have a required property "foo", anyway.

**Comment by untitaker** [comment]
both are correct because type is not required. the question is whether the output types are optimal, and I don't think they are. in practice it is not possible to send an integer with this schema due to the required type.

it's not an important issue because I've now made it a policy in my project to add type everywhere, but it is something I only had to do for jsonschema-gentypes (again, schema validators work fine without type)

**Comment by untitaker** [comment]
I think the problem is not that anybody here is "incorrect" as per spec, but that the spec allows one to write self-contradictory schemas. For example, what does {"type": "integer", "required": ["foo"]} mean? An integer with a property?

**Comment by untitaker** [comment]
I found another problem. In the generated code, `Any` incorrectly imported:

```
jsonschema-gentypes --json-schema <(echo '{}') --python=/dev/stdout
```

Produces:

```
_Root = Any
```

without any preceding import

**Comment by sbrunner** [comment]
This should be fixed with the last version, isn't it?

**Comment by untitaker** [comment]
That works, thank you!
