### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by eugenkleinschmidt** [sbrunner/jsonschema-gentypes#603]
I get a recursion error. See error and json [recursion_error.zip](https://github.com/sbrunner/jsonschema-gentypes/files/12327870/recursion_error.zip)

**Comment by sbrunner** [comment]
The master branch looks to work already, then I just created the version 2.3.0, can you confirm that's working?

**Comment by eugenkleinschmidt** [comment]
Yes, this is working. Thanks! 👍
